// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_d9m3cALxvbEkFde4rccS4k9FCqzwosk',
    appId: '1:586558187807:web:1614fab298b64b7299682a',
    messagingSenderId: '586558187807',
    projectId: 'tok-talk',
    authDomain: 'tok-talk.firebaseapp.com',
    storageBucket: 'tok-talk.appspot.com',
    measurementId: 'G-M0VHTDL8ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARuHNGatn9gftMTNC3gfBCVPvfvymMkpQ',
    appId: '1:586558187807:android:81e34d482d3fd90899682a',
    messagingSenderId: '586558187807',
    projectId: 'tok-talk',
    storageBucket: 'tok-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzW_Ht9Wwg7u1kw7LF5qtyjychAxOZR4',
    appId: '1:586558187807:ios:e300fc68151d724999682a',
    messagingSenderId: '586558187807',
    projectId: 'tok-talk',
    storageBucket: 'tok-talk.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdzW_Ht9Wwg7u1kw7LF5qtyjychAxOZR4',
    appId: '1:586558187807:ios:c6dda7ef0409458f99682a',
    messagingSenderId: '586558187807',
    projectId: 'tok-talk',
    storageBucket: 'tok-talk.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
